version: '3.3'
services:
  mongo_provision:
    build: ./provision
    links:
      - mongodb

  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '80:3000'
    links:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
      - '28017:28017'
